name: Staging Test

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
  staging-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
